# Generated by Django 4.1.5 on 2023-05-01 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_avatar_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='UserExtra',
        ),
    ]
